mendersoftware/mender-helm

- README.md
- mender/templates/secret-s3-artifacts.yaml
- mender/values.yaml
> Add the global.s3.AWS_REGION setting (#18)

- .gitlab-ci.yml
- README.md
- mender/Chart.yaml
- mender/templates/auditlogs-deploy.yaml
- mender/templates/auditlogs-svc.yaml
- mender/templates/deviceconnect-deploy.yaml
- mender/templates/deviceconnect-svc.yaml
- mender/templates/gui-deploy.yaml
- mender/values.yaml
- tests/ci-make-clean.sh
- tests/ci-make-deps.sh
- tests/nats/configmap-nats-config.yaml
- tests/nats/mender-nats.yaml
- tests/nats/service-nats.yaml
Adding new services auditlogs and deviceconnect.
> MEN-4486: Update chart for Mender 2.6.0

- README.md
- mender/templates/api-gateway-deploy.yaml
- mender/templates/api-gateway-secret.yaml
- mender/values.yaml
add a SSL environment variable frontend for the api-gateway container SSL environment variable.
> Pass SSL env variable to api-gateway

- mender/templates/gui-deploy.yaml
> Add HAVE_AUDITLOGS to gui

- README.md
- mender/templates/deployments-deploy.yaml
- mender/templates/secret-s3-artifacts.yaml
- mender/values.yaml
Signed-off-by: Foysal Iqbal <foysal.iqbal.fb@gmail.com>
> Changelog: Use k8s service account to access s3 bucket

- README.md
- mender/Chart.yaml
- mender/templates/gui-deploy.yaml
- mender/values.yaml
> Upgrade Mender to version 2.7.1

- README.md
- mender/Chart.yaml
- mender/templates/gui-deploy.yaml
- mender/values.yaml
> Upgrade Mender to version 3.0.0

- README.md
> Add documentation about `global.auditlogs`

- README.md
- mender/Chart.yaml
- mender/templates/api-gateway-configmap.yaml
- mender/templates/api-gateway-deploy.yaml
- mender/templates/auditlogs-deploy.yaml
- mender/templates/azure-iot-manager-deploy.yaml
- mender/templates/azure-iot-manager-svc.yaml
- mender/templates/create-artifact-worker-deploy.yaml
- mender/templates/deployments-deploy.yaml
- mender/templates/device-auth-deploy.yaml
- mender/templates/deviceconfig-deploy.yaml
- mender/templates/deviceconnect-deploy.yaml
- mender/templates/devicemonitor-deploy.yaml
- mender/templates/gui-deploy.yaml
- mender/templates/inventory-deploy.yaml
- mender/templates/tenantadm-deploy.yaml
- mender/templates/workflows-server-deploy.yaml
- mender/templates/workflows-worker-deploy.yaml
- mender/values.yaml
ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>
> MEN-5154 Adding azure-iot-manager.

- README.md
- mender/templates/create-artifact-worker-deploy.yaml
- mender/templates/workflows-server-deploy.yaml
- mender/templates/workflows-worker-deploy.yaml
- tests/ci-make-deps.sh
> Fix: set WORKFLOWS_NATS_URI for the components based on workflows

- mender/templates/iot-manager-deploy.yaml
> Fix typo in env variable

- mender/templates/gui-deploy.yaml
Support imagePullSecrets for GUI service.
> fix(gui-deploy): add imagePullSecrets

- README.md
- mender/templates/useradm-deploy.yaml
- mender/values.yaml
Updated mountPath for useradm service in enterprise flavour
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
> Updated mountPath for useradm service in enterprise flavour

- README.md
- tests/test-002-create-tenant-and-user-and-login.sh
Fixes: https://gitlab.com/Northern.tech/Mender/mender-helm/-/jobs/1965379733
> Fix tests, useradm CLI is now useradm-enterprise

- README.md
> Fix: docker image for iot-manager in README

- mender/templates/workflows-worker-deploy.yaml
- mender/values.yaml
The values was previously ineffectual - the created secret was unused.
Ticket: MEN-5374
changelog: title
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
> fix: Allow configuring SMTP settings for sending emails

- README.md
- mender/Chart.yaml
- mender/templates/gui-deploy.yaml
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Update version references for Mender 3.2.2.

- mender/values.yaml
> feat: update default Docker tags to mender-3.2.2

- .gitlab-ci.yml
- tests/ci-deps-k8s.sh
> test: use a more recent version of kubectl

- mender/templates/secret-s3-artifacts.yaml
- tests/ci-make-deps.sh
Test pipeline: https://gitlab.com/Northern.tech/Mender/mender-helm/-/pipelines/560375955
> test: update MongoDB helm chart and image tag

- README.md
- mender/Chart.yaml
- mender/templates/gui-deploy.yaml
- mender/values.yaml
- tests/ci-cleanup.sh
- tests/ci-deps-k8s.sh
- tests/ci-make-clean.sh
- tests/ci-make-deps.sh
- tests/ci-make-helm.sh
- tests/ci-test-setup.sh
- tests/ci-test-teardown.sh
- tests/functions.sh
- tests/test-001-wait-for-pods-to-be-ready.sh
- tests/test-002-create-tenant-and-user-and-login.sh
- tests/test-003-test-workflows-server.sh
- tests/tests.sh
- tests/variables.sh
> feat: Mender 3.3.0 release

- README.md
- mender/values.yaml
Ticket: None
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> fix: Upgrade to Mender 3.3.1.

- mender/templates/device-auth-cron-license-count.yaml
Ticket: MEN-5898
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
> chore(deviceauth cronjob): to run the license count

- mender/templates/api-gateway-configmap.yaml
Ticket: MEN-5948
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
> feat: enabled login path via magic links

- README.md
- mender/templates/api-gateway-configmap.yaml
- mender/templates/deployments-deploy.yaml
- mender/templates/device-auth-deploy.yaml
- mender/templates/generate-delta-worker-deploy.yaml
- mender/templates/gui-deploy.yaml
- mender/templates/job-index-devices.yaml
- mender/values.yaml
> Add generate delta worker to the application stack

- README.md
- mender/templates/gui-deploy.yaml
- mender/values.yaml
> feat: upgrade to Mender 3.5.0

- .gitlab-ci.yml
> ci(setup-kubectl): fix cluster namespace selection

- README.md
- mender/Chart.yaml
- mender/templates/gui-deploy.yaml
- mender/values.yaml
> chore: Update service versions to Mender 3.5.1 release.

- mender/templates/db-migration-job.yaml
- mender/templates/index-reporing-job.yaml
> fix: prevents job already exists error

- mender/templates/api-gateway-deploy.yaml
- mender/templates/auditlogs-deploy.yaml
- mender/templates/create-artifact-worker-deploy.yaml
- mender/templates/db-migration-job.yaml
- mender/templates/deployments-deploy.yaml
- mender/templates/device-auth-cron-license-count.yaml
- mender/templates/device-auth-deploy.yaml
- mender/templates/deviceconfig-deploy.yaml
- mender/templates/deviceconnect-deploy.yaml
- mender/templates/devicemonitor-deploy.yaml
- mender/templates/generate-delta-worker-deploy.yaml
- mender/templates/gui-deploy.yaml
- mender/templates/index-reporing-job.yaml
- mender/templates/inventory-deploy.yaml
- mender/templates/iot-manager-deploy.yaml
- mender/templates/redis-deploy.yaml
- mender/templates/reporting-deploy.yaml
- mender/templates/reporting-indexer-deploy.yaml
- mender/templates/tenantadm-deploy.yaml
- mender/templates/useradm-deploy.yaml
- mender/templates/workflows-server-deploy.yaml
- mender/templates/workflows-worker-deploy.yaml
- mender/values.yaml
- tests/values.yaml
Ticket: QA-583
Added default toleration and affinity for `mender-helm-test`. With the `merge` strategy, values can be overridden by specific values.
> Global toleration and affinity

- .gitlab-ci.yml
Ticket: MC-6792
Related to: https://github.com/mendersoftware/sre-tools/pull/293
> Automation to Publish helm charts

- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/templates/secret-artifacts-storage.yaml
Ticket: MEN-6482
https://northerntech.atlassian.net/browse/MEN-6482
Tested with both S3 and Minio deployment.
> Workaround for a permissions error with S3 bucket

- mender/templates/db-migration-job.yaml
This reverts commit 14af3c0afcba7531354999747ae933168656161f.
> Revert "chore: Skip updating NATS consumer in data migration job"

- README.md
- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/templates/_helpers.tpl
- mender/values.yaml
- tests/values-helmci-internal-backing-services.yaml
Workaround for a known issue: https://github.com/bitnami/charts/issues/10843
Also documentation updated: https://github.com/mendersoftware/mender-docs/pull/2155
> Fix issues with mender setup when mongodb is replicaset

- mender/values.yaml
to align with
https://github.com/mendersoftware/integration/blob/master/docker-compose.yml#L60
https://github.com/mendersoftware/integration/blob/master/docker-compose.yml#L270
> chore: aligned service versions with integration

- .gitlab-ci.yml
- README.md
- mender/CHANGELOG.md
- mender/templates/_helpers.tpl
- mender/templates/ingress.yaml
- mender/values.yaml
- tests/ingress-internal-test.sh
- tests/test-001-wait-for-pods-to-be-ready.sh
- tests/test-002-create-tenant-and-user-and-login.sh
- tests/tests.sh
- tests/values-helmci-internal-backing-services.yaml
- tests/values-helmci.yaml
Passing test: https://gitlab.com/Northern.tech/Mender/mender-helm/-/jobs/4717841092#L331
Depends on: https://github.com/mendersoftware/mender-test-containers/pull/382
> feat: added internal Ingress resource

- .gitignore
- README.md
- mender/CHANGELOG.md
- mender/templates/_helpers.tpl
- mender/templates/api-gateway-configmap.yaml
- mender/values.yaml
**Note:** not related to the 3.6 release, it's just part of https://northerntech.atlassian.net/browse/MC-6856
Pipeline passed: https://gitlab.com/Northern.tech/Mender/mender-helm/-/pipelines/944510506
> Converge Helm and kustomize for HM

- .gitlab-ci.yml
- README.md
- mender/CHANGELOG.md
- mender/templates/db-migration-job.yaml
- mender/values.yaml
> fix: pipeline tests after the Mender 3.6 release

- .gitlab-ci.yml
- README.md
- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/templates/gui-deploy.yaml
- mender/values.yaml
Ticket: None
Pipeline with E2E test: https://gitlab.com/Northern.tech/Mender/mender-helm/-/pipelines/973024287
> feat: set Mender 3.6.1 image tags

- .gitlab-ci.yml
> fix: failing tests because of lack of resources

- README.md
- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/templates/deployments-deploy.yaml
- mender/templates/deployments-storage-daemon-cronjob.yaml
- mender/values.yaml
> feat: add the `deployments.directUpload.skipVerify` parameter

- .gitlab-ci.yml
> chore: added RUN_PLAYGROUND pipeline to spin up a temporay EKS cluster

- README.md
- mender/CHANGELOG.md
- mender/templates/gui-svc.yaml
- mender/values.yaml
To align HM with the Helm Chart: this value is already present on the HM instance
> Added Port for the Error server block on the gui

- .gitlab-ci.yml
- tests/test-002-create-tenant-and-user-and-login.sh
- tests/values-opensource.yaml
> Mender Opensource test setup

- mender/templates/auditlogs-deploy.yaml
- mender/templates/create-artifact-worker-deploy.yaml
- mender/templates/deployments-deploy.yaml
- mender/templates/device-auth-deploy.yaml
- mender/templates/deviceconfig-deploy.yaml
- mender/templates/deviceconnect-deploy.yaml
- mender/templates/devicemonitor-deploy.yaml
- mender/templates/generate-delta-worker-deploy.yaml
- mender/templates/inventory-deploy.yaml
- mender/templates/iot-manager-deploy.yaml
- mender/templates/useradm-deploy.yaml
- mender/templates/workflows-server-deploy.yaml
- mender/templates/workflows-worker-deploy.yaml
> fix: automigrate command newline fix

- mender/values.yaml
> chore: updated traefik to latest version

- mender/templates/db-migration-job.yaml
Fixes: https://gitlab.com/Northern.tech/Mender/mender-helm/-/jobs/5230233367
> fix: using prerelease secret with migration jobs

- README.md
- mender/templates/auditlogs/deployment.yaml
- mender/templates/create-artifact-worker/deployment.yaml
- mender/templates/deployments/deployment.yaml
- mender/templates/device-auth/deployment.yaml
- mender/templates/deviceconfig/deployment.yaml
- mender/templates/deviceconnect/deployment.yaml
- mender/templates/devicemonitor/deployment.yaml
- mender/templates/inventory/deployment.yaml
- mender/templates/iot-manager/deployment.yaml
- mender/templates/secrets/secret-artifacts-storage.yaml
- mender/templates/secrets/secret-mongodb-common.yaml
- mender/templates/tenantadm/deployment.yaml
- mender/templates/useradm/deployment.yaml
- mender/templates/workflows/deployment-server.yaml
- mender/templates/workflows/deployment-worker.yaml
- mender/values.yaml
Follow-up from the original PR: https://github.com/mendersoftware/mender-helm/pull/87 which is stale (the external contributor didn't answer), but the helm chart needs the feature.
> Allow to use external secrets - 2nd

- README.md
- mender/CHANGELOG.md
- mender/values.yaml
Follow-up from https://github.com/mendersoftware/mender-helm/pull/203
> Certificate management documentation

- README.md
- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/templates/deviceconnect/deployment.yaml
- mender/values.yaml
> feat: graceful shutdown for deviceconnect

- .gitlab-ci.yml
> Don't run eks tests during version bump

- README.md
- mender/CHANGELOG.md
- mender/templates/_helpers.tpl
- mender/templates/api-gateway/deployment.yaml
- mender/templates/auditlogs/_podtemplate.yaml
- mender/templates/deployments/_podtemplate.yaml
- mender/templates/deployments/cronjob.yaml
- mender/templates/device-auth/_podtemplate.yaml
- mender/templates/device-auth/cronjob.yaml
- mender/templates/deviceconfig/_podtemplate.yaml
- mender/templates/deviceconnect/_podtemplate.yaml
- mender/templates/devicemonitor/_podtemplate.yaml
- mender/templates/generate-delta-worker/deployment.yaml
- mender/templates/gui/deployment.yaml
- mender/templates/inventory/_podtemplate.yaml
- mender/templates/iot-manager/_podtemplate.yaml
- mender/templates/serviceaccount.yaml
- mender/templates/tenantadm/_podtemplate.yaml
- mender/templates/useradm/_podtemplate.yaml
- mender/templates/workflows/_podtemplate.yaml
- mender/values.yaml
Took @bdomars 's wonderful work, and extended to support pre-release helm hooks
> Added Serviceaccount support

- .gitlab-ci.yml
- README.md
- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/templates/gui/deployment.yaml
- mender/values.yaml
Chart version 5.4.1 with Mender version 3.7.1
Ticket: None
Changelog: Mender Version 3.7.1
> Mender version 3.7.1

- README.md
- mender/CHANGELOG.md
- mender/templates/_helpers.tpl
> Minio and Mongo fixes

- mender/templates/api-gateway/configmap.yaml
> feat: add OpenId Connect endpoints as unauth ones

- README.md
- mender/CHANGELOG.md
- mender/templates/_helpers.tpl
- mender/templates/api-gateway/configmap.yaml
- mender/templates/auditlogs/_podtemplate.yaml
- mender/templates/create-artifact-worker/deployment.yaml
- mender/templates/deployments/_podtemplate.yaml
- mender/templates/device-auth/_podtemplate.yaml
- mender/templates/deviceconfig/_podtemplate.yaml
- mender/templates/deviceconnect/_podtemplate.yaml
- mender/templates/devicemonitor/_podtemplate.yaml
- mender/templates/generate-delta-worker/deployment.yaml
- mender/templates/gui/deployment.yaml
- mender/templates/inventory/_podtemplate.yaml
- mender/templates/iot-manager/_podtemplate.yaml
- mender/templates/tenantadm/_podtemplate.yaml
- mender/templates/useradm/_podtemplate.yaml
- mender/templates/workflows/_podtemplate.yaml
- mender/values.yaml
* Replaced minio specific gateway with a generic storage_gateway service, that could work for both minio and Amazon S3
* Added customEnvs options
> Switch to storage gateway from minio and CustomEnvs

- mender/CHANGELOG.md
- mender/Chart.yaml
> Bump chart to v5.5.0

- mender/CHANGELOG.md
- mender/templates/create-artifact-worker/deployment.yaml
- mender/templates/generate-delta-worker/deployment.yaml
- mender/templates/workflows/_podtemplate.yaml
> Fix NATS address when global.nats.existingSecret is defined

- mender/values.yaml
> Yaml formatting fixup

- mender/CHANGELOG.md
- mender/templates/api-gateway/deployment.yaml
- mender/templates/auditlogs/_podtemplate.yaml
- mender/templates/create-artifact-worker/deployment.yaml
- mender/templates/deployments/_podtemplate.yaml
- mender/templates/deployments/cronjob.yaml
- mender/templates/device-auth/_podtemplate.yaml
- mender/templates/device-auth/cronjob.yaml
- mender/templates/deviceconfig/_podtemplate.yaml
- mender/templates/deviceconnect/_podtemplate.yaml
- mender/templates/devicemonitor/_podtemplate.yaml
- mender/templates/generate-delta-worker/deployment.yaml
- mender/templates/gui/deployment.yaml
- mender/templates/inventory/_podtemplate.yaml
- mender/templates/iot-manager/_podtemplate.yaml
- mender/templates/tenantadm/_podtemplate.yaml
- mender/templates/useradm/_podtemplate.yaml
- mender/templates/workflows/_podtemplate.yaml
- mender/values.yaml
> Indent issue with custom imagePullSecrets

- mender/CHANGELOG.md
- mender/templates/deployments/cronjob.yaml
> Fix storage secret for deployments storage daemon

- mender/CHANGELOG.md
- mender/Chart.yaml
> Release version 5.5.1

- mender/templates/api-gateway/configmap.yaml
> feat: support for X-MEN-RBAC-Releases-Tags

- README.md
- mender/CHANGELOG.md
- mender/templates/_helpers.tpl
- mender/templates/api-gateway/configmap.yaml
- mender/templates/api-gateway/deployment.yaml
- mender/templates/auditlogs/deployment.yaml
- mender/templates/create-artifact-worker/deployment.yaml
- mender/templates/deployments/_podtemplate.yaml
- mender/templates/deployments/deployment.yaml
- mender/templates/device-auth/_podtemplate.yaml
- mender/templates/device-auth/deployment.yaml
- mender/templates/deviceconfig/deployment.yaml
- mender/templates/deviceconnect/deployment.yaml
- mender/templates/devicemonitor/deployment.yaml
- mender/templates/generate-delta-worker/deployment.yaml
- mender/templates/gui/deployment.yaml
- mender/templates/inventory/_podtemplate.yaml
- mender/templates/inventory/deployment.yaml
- mender/templates/iot-manager/deployment.yaml
- mender/templates/tenantadm/deployment.yaml
- mender/templates/useradm/_podtemplate.yaml
- mender/templates/useradm/deployment.yaml
- mender/templates/workflows/deployment-server.yaml
- mender/templates/workflows/deployment-worker.yaml
- mender/values.yaml
Changes:
* forcing passHostHeader to false in the traefik conf: same conf as HM
* default Referrer-Policy: no referrer: same conf as HM
* bump traefik to 2.10.7
* feat: added support for custom updateStrategy
* fix missing auditlog variable in the device auth service
* fix Redis environment variables when using an external Redis
* feat: added `global.redis.existingSecret` option
> v5.5.1 improvements, fixes, and staging alignments

- .gitlab-ci.yml
- Makefile
- README.md
- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/values.yaml
> Upgrade to Mender v3.7.2

- .gitlab-ci.yml
Switch Mender-helm CICD to the Hetzner host.
> Switch CICD to hetzner host

- .gitlab-ci.yml
Ticket: OP-656
Requires: https://github.com/NorthernTechHQ/sre-iac/pull/4
Follow-ups:
> Move aws auth to oidc mapping

- .gitlab-ci.yml
- README.md
- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/values.yaml
> Bump to Mender 3.7.3

- .gitlab-ci.yml
- mender/Chart.yaml
> Bump to version 5.6.1

- .gitlab-ci.yml
- README.md
- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/values.yaml
And chart to 5.6.2
Ticket: None
> Bump to mender 3.7.4

- mender/CHANGELOG.md
- mender/templates/gui/deployment.yaml
> chore: not using HAVE_ENTERPRISE when in hosted

- README.md
- mender/CHANGELOG.md
- mender/templates/_helpers.tpl
- mender/templates/api-gateway/deployment.yaml
- mender/templates/api-gateway/podMonitor.yaml
- mender/templates/auditlogs/_podtemplate.yaml
- mender/templates/deployments/_podtemplate.yaml
- mender/templates/device-auth/_podtemplate.yaml
- mender/templates/deviceconfig/_podtemplate.yaml
- mender/templates/deviceconnect/_podtemplate.yaml
- mender/templates/devicemonitor/_podtemplate.yaml
- mender/templates/gui/deployment.yaml
- mender/templates/inventory/_podtemplate.yaml
- mender/templates/iot-manager/_podtemplate.yaml
- mender/templates/tenantadm/_podtemplate.yaml
- mender/templates/useradm/_podtemplate.yaml
- mender/templates/workflows/_podtemplate.yaml
- mender/values.yaml
> PodMonitor for monitoring traefik and probesOverrides

- README.md
- mender/CHANGELOG.md
- mender/templates/secrets/secret-smtp.yaml
- mender/templates/workflows/_podtemplate.yaml
- mender/values.yaml
Don't create the smtp secret when an existingSecret is created
Ticket: MC-7456
> fix: added global.smtp.existingSecret

- mender/Chart.yaml
> chore: bump to 5.7.1

- mender/CHANGELOG.md
Which was not so clear
Ticket: MC-7456
> chore: updating changelog doc

- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/templates/deployments/_podtemplate.yaml
> fix: managing redis existingSecret when set

- README.md
- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/templates/_helpers.tpl
- mender/templates/deployments/_podtemplate.yaml
- mender/templates/tests/test-mender.yaml
- mender/values.yaml
Conflicts resolution from https://github.com/mendersoftware/mender-helm/pull/301
* Added helm chart tests.
* Default `updateStrategy.rollingUpdate.maxUnavailable` to 0 to complete the helm upgrade with
all the services running.
* Removed `helm.sh/chart` annotation to avoid a full restart every release.
* Added Redis to the Deployments service
> Align prod with Master - v5.8.0

- mender/CHANGELOG.md
- mender/Chart.yaml
- mender/templates/NOTES.txt
- mender/templates/gui/deployment.yaml
> fix: correctly setup the Mender Version

- README.md
- mender/templates/gui/deployment.yaml
- mender/templates/gui/hpa.yaml
- mender/values.yaml
Added Horizontal Pod Autoscaler resource to the gui container, to scale it automatically when the service experiences more load.
Ticket: MC-7600
> Add gui hpa

- .gitlab-ci.yml
This could happen in pipeline with cached jobs
> ci: fix remote repository already existing

- .gitlab-ci.yml
In some conditions the upstream pr branch could diverge from the local branch. With this fix it should rebase the upstream changes locally.
For example: https://gitlab.com/Northern.tech/Mender/mender-helm/-/jobs/8049202233#L251
> ci: fix diverging PRs

- mender/values-staging.yaml
> chore: manually set the staging rc.2 tag

- .gitlab-ci.yml
Backporting https://github.com/mendersoftware/mender-helm/pull/377
> Backporting "Include only branch tags in the changelog"

- release-please-config.json
> chore: release 5.11.2

- UPGRADE_from_v5_to_v6.md
> typo:  UPGRADE_from_v5_to_v6.md

- mender/Chart.yaml
- mender/values-staging.yaml
To address the upcoming fix on the pipeline
> chore: manually bump staging

- .gitlab-ci.yml
This prevents an error during updating the load balancer ingress
> ci: fix elb permission error

- .gitlab-ci.yml
This reverts commit bbb83fc204fe8528f187999d5bebf00d7e6c2293.
> revert: fix elb permission error

- mender/templates/deviceconnect/_podtemplate.yaml
- mender/templates/workflows/_podtemplate.yaml
Aligned the nats_uri of the deviceconnect and the workflows definitions to the other services
Ticket: None
> refac: consistency between nats_uri declaration

- mender/templates/auditlogs/_podtemplate.yaml
> fix: use correct device_auth key

- mender/templates/auditlogs/_podtemplate.yaml
- mender/templates/deployments/_podtemplate.yaml
- mender/templates/device-auth/_podtemplate.yaml
- mender/templates/deviceconfig/_podtemplate.yaml
- mender/templates/deviceconnect/_podtemplate.yaml
- mender/templates/devicemonitor/_podtemplate.yaml
- mender/templates/inventory/_podtemplate.yaml
- mender/templates/iot-manager/_podtemplate.yaml
- mender/templates/tenantadm/_podtemplate.yaml
- mender/templates/useradm/_podtemplate.yaml
- mender/templates/workflows/_podtemplate.yaml
Introduced by merging 3c0419477a68fc3ebb81330591164f2dc7349bc5
> chore: Fix format strings for internal addresses

- .gitlab-ci.yml
> ci: correctly handling changelogs for stable releases

- .github/dependabot.yml
To trigger the automated versioning
TIcket: none
> ci: switch commit messages to fix

- README.md
> docs: Fixed documented default for redis state

- mender/templates/api-gateway/configmap.yaml
as in: https://github.com/NorthernTechHQ/alvaldi-helm/pull/28
> MC-6867 - feat: added Mender HTTP headers to display the chart version + name

- .gitlab-ci.yml
- Makefile
- README.md
- mender/values.yaml
First time doing this, please make sure it's correct
> chore: upgrade helm chart for Mender 3.7.11 release

- mender/Chart.yaml
> fix: upgrade helm chart for Mender 3.7.11 release

- README.md
- mender/templates/deployments/_podtemplate.yaml
- mender/values.yaml
> feat: add configurable artifacts upload size

- mender/values.yaml
Avoid nil pointer exception when default.image.tag is not set
Ticket: MC-7961
> fix: display Mender Version

- mender/templates/gui/deployment.yaml
> fix: removed duplicated PeriodSeconds

- .gitlab-ci.yml
> ci: switch pipeline image to bookworm

- mender/values.yaml
> fix: increase default limits for delta generator
