.gitlab-ci.yml
Makefile
README.md
tests/ci-deps-k8s.sh
tests/ci-make-clean.sh
tests/ci-make-deps.sh
tests/ci-make-helm.sh
tests/ci-test-setup.sh

MEN-4486: [pipeline] Run tests in Hosted Mender staging cluster
This commit reworks the test job and the helper scripts to run the tests
in HM staging, namespace mender-helm-tests.
It assumes only one CI pipeline is running in parallel.
In addition:
* [Makefile] Set shell to /bin/bash
As sh complains on invalid syntax
* [README] Document the obvious: build before install
* [ci-deps-k8s] Update URL for stable helm repository
The googleapis.com one is deprecated and prints a warning to switch to
the new one.
* [tests/] Split ci-deps-k8s.sh into two scripts: install and deploy
So that locally we can run the deploy one assuming all dependencies are
in place.
* [ci-make-helm] Use relative path instead of hardcoded CI path
* [ci-make-helm] User friendly exit when no credentials in env
* …

MEN-4486: [pipeline] Run tests in Hosted Mender staging cluster

---

.gitlab-ci.yml
tests/test-001-wait-for-pods-to-be-ready.sh

So that we can verify the code before it can access protected env variables.

[pipeline] Run install test only for master jobs

---

mender/templates/api-gateway-svc.yaml

If helm chart is deployed without SSL support, the api-gateway-svc mapping
of the SSL port should also be removed.
Signed-off-by: Alexandru Ionita <alexandru.ionita@gmail.com>

Remove SSL port mapping svc->pod if SSL disabled

---

mender/templates/api-gateway-configmap.yaml
mender/templates/api-gateway-deploy.yaml

In case no SSL termination is desired in the api-gateway, that should be
possible and the traefik configuration should be consistent with the
supplied configuration parameter `api_gateway.env.SSL`.
Signed-off-by: Alexandru Ionita <alexandru.ionita@gmail.com>

Handle no SSL termination in the api-gateway

---

.gitlab-ci.yml
README.md
tests/ci-make-clean.sh
tests/ci-make-deps.sh

Downgrade mongodb Chart version to 10.21.1, as 10.21.2 is not released

---

mender/templates/gui-deploy.yaml

Not in use anymore by the gui container

Remove MENDER_DEB_PACKAGE_VERSION

---

mender/templates/deployments-deploy.yaml
mender/templates/deviceconfig-deploy.yaml
mender/templates/deviceconnect-deploy.yaml
mender/templates/gui-deploy.yaml
mender/templates/useradm-deploy.yaml
mender/templates/workflows-worker-deploy.yaml

Use `auditlogs.enabled` as flag to enable auditlogs across services

---

mender/templates/api-gateway-configmap.yaml
mender/templates/api-gateway-deploy.yaml

Replace api-gateway TCP probes with readiness and liveness probes
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>

Replace api-gateway TCP probes with readiness and liveness probes

---

mender/templates/device-auth-deploy.yaml
mender/values.yaml

Added support for deviceauth enterprise in Helm Chart
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>

Added support for deviceauth enterprise in Helm Chart

---

mender/templates/api-gateway-deploy.yaml

The "periodseconds" field is present several times in the api-gateway readiness probe.
See [MEN-5407](https://tracker.mender.io/browse/MEN-5407)

Fix readiness probe for api-gateway deployment

---

mender/templates/create-artifact-worker-deploy.yaml
mender/templates/workflows-worker-deploy.yaml

Depends on mendersoftware/workflows-enterprise#359

fix: Replace Hosted Mender references with `global.url` in workflows

---

README.md
mender/templates/api-gateway-deploy.yaml
mender/templates/auditlogs-deploy.yaml
mender/templates/create-artifact-worker-deploy.yaml
mender/templates/deployments-deploy.yaml
mender/templates/device-auth-deploy.yaml
mender/templates/deviceconfig-deploy.yaml
mender/templates/deviceconnect-deploy.yaml
mender/templates/devicemonitor-deploy.yaml
mender/templates/gui-deploy.yaml
mender/templates/inventory-deploy.yaml
mender/templates/iot-manager-deploy.yaml
mender/templates/tenantadm-deploy.yaml
mender/templates/useradm-deploy.yaml
mender/templates/workflows-server-deploy.yaml
mender/templates/workflows-worker-deploy.yaml
mender/values.yaml

Allow to select the node via helm values.
This contribution allows to use this chart in Kubernetes clusters, where the default architecture is not x86_64 for the nodes.
With this change, the users will be able to select their own nodes other than the default one, which can be based on x86_64 as that is the only supported architecture as far I see.
The node selection is done based on a pattern widely used among popular helm charts.
Some examples from other helm charts:
ingress-nginx: https://github.com/kubernetes/ingress-nginx/search?q=nodeSelector
* https://github.com/kubernetes/ingress-nginx/blob/15b0aba03b700daacf0e9a3f5154ca1b9f77ee18/charts/ingress-nginx/templates/controller-deployment.yaml#L189
* https://github.com/kubernetes/ingress-nginx/blob/15b0aba03b700daacf0e9a3f5154ca1b9f77ee18 …

Allow "nodeSelector" option on all deployments

---

README.md
mender/Chart.yaml
mender/templates/api-gateway-configmap.yaml
mender/templates/device-auth-deploy.yaml
mender/templates/gui-deploy.yaml
mender/templates/iot-manager-svc.yaml
mender/templates/redis-deploy.yaml
mender/templates/redis-svc.yaml
mender/templates/tenantadm-deploy.yaml
mender/templates/useradm-deploy.yaml
mender/values.yaml

Add a redis pod and configure deviceauth and useradm to connect to it
enabling rate limits and caching of JWT tokens. At the same time, set
default rate limits in tenantadm.
Ticket: MEN-5270

feat(rate limits): set default rate limits and caching in Mender Enterprise

---

README.md
mender/templates/secret-s3-artifacts.yaml
mender/values.yaml

Setting a value for the AWS_EXTERNAL_URI env variable in the deployments
service, it is possible to use an external URL for the S3 storage when
generating presigned download URLs and an internal URL for all the other
API calls (e.g., uploading of artifacts). If AWS_EXTERNAL_URI is not
set, it defaults to AWS_URI (internal URL), making this change
back-compatible.
Ticket: MEN-5280
Requires: https://github.com/mendersoftware/deployments/pull/728

feat: add support for the AWS_EXTERNAL_URI deployments' setting

---

README.md
mender/templates/api-gateway-deploy.yaml
mender/templates/auditlogs-deploy.yaml
mender/templates/create-artifact-worker-deploy.yaml
mender/templates/deployments-deploy.yaml
mender/templates/device-auth-deploy.yaml
mender/templates/deviceconfig-deploy.yaml
mender/templates/deviceconnect-deploy.yaml
mender/templates/devicemonitor-deploy.yaml
mender/templates/inventory-deploy.yaml
mender/templates/iot-manager-deploy.yaml
mender/templates/tenantadm-deploy.yaml
mender/templates/useradm-deploy.yaml
mender/templates/workflows-server-deploy.yaml
mender/templates/workflows-worker-deploy.yaml
mender/values.yaml

Allows to add annotations on all mender pods.
Like `istio-injection: enabled` or `linkerd.io/inject: disabled`
Signed-off-by: Benjamin Texier <benjamin.texier@outlook.com>

feat: add podAnnotations for all pods

---

README.md
mender/templates/api-gateway-deploy.yaml
mender/templates/api-gateway-svc.yaml
mender/values.yaml

The commit "feat: Reuse service port for api-gateway entrypoints" in #90 made the `api_gateway` deployment configurable using the service ports. However, I ran into some problems using this:
1. In a Red Hat OpenShift cluster, the container ports cannot be privileged (<1024) ports, so it is common to have the service on privileged ports (80/443) and the container listening on non-privileged ports (8888/8443).
2. The two containerPort settings and readiness/liveness/startup probes are not configurable but need to use the same ports.
I added new settings `api_gateway.httpPort` and `api_gateway.httpsPort` that are used to configure all the ports in the deployment, and also the target ports in the service.

feat: Configurable container ports for api-gateway

---

mender/templates/useradm-deploy.yaml

This is required for SSO/SAML to work.

chore: Add USERADM_BASE_URL env variable

---

mender/templates/db-migration-job.yaml
mender/templates/index-reporing-job.yaml
mender/templates/secret-docker-registry-prerelease.yaml
mender/templates/secret-mongodb-common-prerelease.yaml
mender/values.yaml

Added DB Migration chart hook to apply DB migrations before starting an helm deployment.
Ref: https://northerntech.atlassian.net/browse/MC-6386

DB Migration Chart Hook 

---

README.md
mender/templates/api-gateway-deploy.yaml
mender/templates/auditlogs-deploy.yaml
mender/templates/create-artifact-worker-deploy.yaml
mender/templates/db-migration-job.yaml
mender/templates/deployments-deploy.yaml
mender/templates/device-auth-deploy.yaml
mender/templates/deviceconfig-deploy.yaml
mender/templates/deviceconnect-deploy.yaml
mender/templates/devicemonitor-deploy.yaml
mender/templates/gui-deploy.yaml
mender/templates/gui-svc.yaml
mender/templates/inventory-deploy.yaml
mender/templates/iot-manager-deploy.yaml
mender/templates/redis-deploy.yaml
mender/templates/tenantadm-deploy.yaml
mender/templates/useradm-deploy.yaml
mender/templates/workflows-server-deploy.yaml
mender/templates/workflows-worker-deploy.yaml
mender/values.yaml

This PR adds support for `securityContext` in both the pod and container spec. 
The newly added values each have an `enabled` switch, which is disabled by default for backward compatibility.
For the `api_gateway` securityContext to work, the internal listening ports have been moved out of the privileged port range.
The `gui` container can not work without upstream adjustments of the container image. Currently, the port used by nginx is fixed to `80`. I added `gui.httpPort` to be able to change the port when it gets configurable in the `gui` image.
Documentation for all added parameters is provided as well. 
Let me know if you require any adjustments.

Add podSecurityContext and containerSecurityContext

---

README.md
mender/templates/secret-smtp.yaml
mender/values.yaml

This PR updates the STMP configuration to match what is defined in the [config.yaml of the workflows repo](https://github.com/mendersoftware/workflows/blob/master/config.yaml#L72-L95)..
Also, I couldn't find where `EMAIL_SENDER` and `SMTP_SSL` is being used.. are these still supported?

fix smtp configuration according to the config.yaml in workflows repo

---

README.md
mender/CHANGELOG.md
mender/Chart.yaml
mender/templates/auditlogs-deploy.yaml
mender/templates/create-artifact-worker-deploy.yaml
mender/templates/db-migration-job.yaml
mender/templates/deployments-deploy.yaml
mender/templates/deployments-storage-daemon-cronjob.yaml
mender/templates/device-auth-cron-license-count.yaml
mender/templates/device-auth-deploy.yaml
mender/templates/deviceconfig-deploy.yaml
mender/templates/deviceconnect-deploy.yaml
mender/templates/devicemonitor-deploy.yaml
mender/templates/generate-delta-worker-deploy.yaml
mender/templates/gui-deploy.yaml
mender/templates/inventory-deploy.yaml
mender/templates/iot-manager-deploy.yaml
mender/templates/tenantadm-deploy.yaml
mender/templates/useradm-deploy.yaml
mender/templates/workflows-server-deploy.yaml
mender/templates/workflows-worker-deploy.yaml
mender/values.yaml

Using a `global.registry.image.tag` for Mender deployment (defult to `mender-3.4`) so to not specify it in every deployment.
This leads also a better user experience with selecting a different Mender version within the same Helm Chart.
Ticket: https://northerntech.atlassian.net/browse/MC-6798

Global registry.image.tag

---

mender/templates/device-auth-cron-license-count.yaml
mender/values.yaml

Per the 3.5.x documentation [1], Device License Count is only available with Enterprise.
Avoid ImagePullBackOff and ErrImagePull by not deploying the device-auth-license-count cron job when global.enterprise is disabled.
[1] https://github.com/mendersoftware/mender-docs/blob/3.5.x/07.Server-installation/07.Device-license-count/docs.md

fix: device-auth-license-count ImagePullBackOff

---

mender/templates/db-migration-job.yaml

After adding the possiblity to migrate the NATS consumer configuration, this might break forward compatibility for older versions which prevents downgrading. Since the newer version works with consumer configurations from older versions we don't force consumer reconfigurations in this job.

chore: Skip updating NATS consumer in data migration job

---

mender/templates/secret-artifacts-storage.yaml

Ticket: MC-6482
`STORAGE_BUCKET` is going to replace the old `AWS_BUCKET` variable, but this is still used on old deployments.
Adding both AWS_BUCKET and STORAGE_BUCKET vars to the `secret-artifacts-storage.yaml` to have backward compatiblity

Backward compatible AWS_BUCKET variable

---

.gitlab-ci.yml
tests/affinity-x86_64-standard.yaml
tests/ci-deps-k8s.sh
tests/values-helmci.yaml

1. Added a custom pipeline toolbox image: this is built at the start of the pipeline and pushed to Gitlab Registry. It'll be reused from the downstream steps. It's cached for subsequently faster builds.
2. Added temporary EKS cluster creation: not using the Staging EKS cluster: this because in the future we may move the staging cluster behind VPN. Also tried to use Minikube/KinD/K3s in a VM but it's a messy setup and leads to unexpected results. Found that the best solution is to spin up a temporary EKS cluster. Tests is getting slower, though.
3. Refactored the helm install, by using the `./mender` folder instead of the packaged mender helm chart
4. Added multiple upgrade tests: from the published mender chart with `appVersion: mender-3.3` to the `./mender` chart with `appVersion: …

Refactor helm chart integration tests

---

.gitlab-ci.yml

The exact mender tag is specified in the Gitlab CICD variables: `MENDER_3_6_RELEASE_TAG`, now set to `mender-3.6.0-build3`

chore: added 3.6 upgrade tests

---

.gitlab-ci.yml

This reverts commit dd0e3510bcf518ea127c6d46b9eeff7a20174f8c.
Too early merge: it has to be merged with the 3.6 branch

Revert "chore: added 3.6 upgrade tests"

---

mender/CHANGELOG.md
mender/Chart.yaml
mender/templates/_helpers.tpl

always using the redis `master` address instead of the `headless` one, which leads to sporadic errors in writing when you have replicas in place.

Fix redis master address

---

.gitlab-ci.yml

This missing step prevents the publish pipeline to succeed. With this PR we want to have it back.

Build step is missing when publishing

---

mender/templates/api-gateway/deployment.yaml
mender/templates/api-gateway/secret.yaml
mender/templates/device-auth/deployment.yaml
mender/templates/device-auth/secret.yaml
mender/templates/tenantadm/deployment.yaml
mender/templates/tenantadm/secret.yaml
mender/templates/useradm/deployment.yaml
mender/templates/useradm/secret.yaml

The current way of creating the secrets for certs via the Helm charts does not  work well with external secret management tools like Vault and Vault webhook. 
This PR adds an existingSecret parameter to all `certs` to not have the Helm chart render the secrets and instead letting the external tools manage them.

Option to use existing secrets for certificates

---

mender/CHANGELOG.md
mender/Chart.yaml

Changes from 5.2.4:
* Added support to external Image Pull Secrets
* Added support to extraArgs to the `api_gateway` service
* Traefik updated to `v2.10.4`
* You can now add pre-existing `priorityClassName` to the resources
* Added PodDisruptionBudget resources to the most critical services
* Added option to use existing secrets for certificates (thanks @bdomars)
* Allow to use external secrets for NATS, MongoDB, and S3 (thanks @benjamin-texier)

New helm release: 5.2.5 from master

---

mender/templates/deployments/cronjob.yaml

Hello!
I noticed that the helm chart cannot render the yaml correctly if you add pod annotations to the deployments section. I tracked this down to be a simple indentation miss.

fix: indent cronjob annotations correctly

---

.gitlab-ci.yml

Ticket: MC-7138
`--set global.s3.AWS_FORCE_PATH_STYLE="true"` is rendered as a bool, not string. It would have been:
`--set global.s3.AWS_FORCE_PATH_STYLE=\"true\"`. Anyway, the default value in the `mender/values.yaml` is already `"true"`, so we can omit this setting here.

chore: fix R2 setup test

---

tests/ci-deps-k8s.sh
tests/ci-make-deps.sh
tests/minio-standalone/minio.yaml

as a drop-in replacement of the deprecated
https://helm.min.io/, still including the old-licensed image
Ticket: QA-641

Helm minio deprecation

---

.gitlab-ci.yml

Added stage version-bump to set new mender tags in the values-prod.yaml or values-staging.yaml when a remote pipeline is triggered.

chore: added pipeline version bump

---

.gitlab-ci.yml

when the pipeline is triggered we don't need to run the license source check, which is not working for this kind of process

Excluding license source check in trigger

---

.gitlab-ci.yml

Ticket: MC-7268
Sometimes spot instances aren't available. This option allows to fall back to on-demand instances in the tests.

Added option to not to use spot instances

---

mender/CHANGELOG.md
mender/Chart.yaml
mender/templates/api-gateway/configmap.yaml

When the api_gateway.authRateLimit is set, a malformed authorization header error is displayed at login. This fix solves the issue

Malformed auth header when authRateLimit is set

---

README.md
mender/CHANGELOG.md
mender/Chart.yaml
mender/templates/_helpers.tpl
mender/templates/api-gateway/deployment.yaml
mender/templates/inventory/_podtemplate.yaml
mender/values.yaml

* `generate_delta_worker`: don't enforce tags for the image.
* Added `api_gateway.accesslogs` parameter to enable/disable access logs.
* Bump traefik image to v2.11.2
* Move from megabytes to mebibytes for consistency.
* Added `inventory.mongodbExistingSecret` to override the default MongoDB secret.

Fixes and alignements to saas

---

mender/templates/inventory/_podtemplate.yaml

When a global.mongodb.existingSecret is set, the mongodb override for the inventory doesn't work. This fixes it.
Ticket: MC-7302

fix: mongodb override with global existingsecret

---

README.md
mender/templates/_helpers.tpl
mender/values.yaml

we're packaging mender as a sub-chart. which resulted in a relatively long chart names combination:
```
Invalid value: `our-custom-helm-chart-mender-deployments-storage-daemon` must be no more than 52 characters
```

allow overriding name and fullname

---

mender/templates/api-gateway/service.yaml

The template checks for a value that is different from the one using in the line after to set the value.
Looking into how it is done for http just below seems like a typo to me.

Fix naming problem in templates using api_gateway and NodePort

---

mender/CHANGELOG.md
mender/values.yaml

chore: bump default nats image to 2.9.20

---

mender/CHANGELOG.md
mender/Chart.yaml
mender/templates/gui/deployment.yaml

This fix allows displaying the integration button on the Mender 3.6 release
Ticket: None

fix: display integrations button on 3.6

---

mender/CHANGELOG.md
mender/Chart.yaml
mender/templates/generate-delta-worker/deployment.yaml

Fix using an external secret in the generate delta worker service, when using MongoDB subchart.
Ticket: MC-7496

Generate delta worker mongo secret

---

README.md
mender/CHANGELOG.md
mender/Chart.yaml
mender/templates/generate-delta-worker/service.yaml
mender/templates/generate-delta-worker/statefulset.yaml
mender/values.yaml

Changes the `generate-delta-worker` workload from Deployment to StatefulSet and exposes volume claim template parameters in the values.

feat: Change `generate-delta-worker` to StatefulSet and add persistence

---

mender/CHANGELOG.md
mender/Chart.yaml
mender/templates/_helpers.tpl

The regular expression in the hostname rule was using incompatible Traefik v2 regex.

fix(traefik v3): Invalid host regex for default storage proxy URL

---

.gitlab-ci.yml

With the --unreleased flag, only the last release were added to the CHANGELOG.md, so the old history would have been lost. With this change, we'll just prepend the new git cliff release.
[Wrong CHANGELOG patch](https://github.com/mendersoftware/mender-helm/pull/346/commits/da9a4ef2e668fa0fa057321e0aac287b01f38997#diff-d2cbe88096a4c24cd4a33d862fe49df122c543515c8b811b79f67818f655982e)
Likely good CHANGELOG patch:
```
- Add gui hpa ([8f6d9f4](https://github.com/mendersoftware/mender-helm.git/commit/8f6d9f46c0c9db16939a8c851ed4bda21e7ca5f3)) 
Added Horizontal Pod Autoscaler resource to the gui container, to scale
it automatically when the service experiences more load.
* Fix invalid regexp in default storage proxy rule.
* Change `generate_delta_worker` to StatefulSet and add `persistence` …
```

ci: fix changelog append on top

---

.gitlab-ci.yml
release-please-config.json

For some reason the `--prepend` option is not working well with the previous changelog: it is adding the new changes in the [middle of the changelog file](https://github.com/mendersoftware/mender-helm/pull/346/files#diff-d2cbe88096a4c24cd4a33d862fe49df122c543515c8b811b79f67818f655982eR79). 
For this reason my purpose is to generate the full changelog history, also to adhere fully to the new standard.
Also, this fixes the commit signoff missing

Fix release please - iteration #2

---

.gitlab-ci.yml

@alfrunes I saw that in the same runner, sometime old github remote could "survive", and could be from past try and tests, so there is no guarantees the `github` remote is the good one.
This PR address this behavior by always setting a new unique github remote `github-${CI_JOB_ID}`, and removes it in the `after_script`. Successfully tested in a [sample pipeline](https://gitlab.com/Northern.tech/northerntechhq/nt-boilerplate-pipeline/-/jobs/8070161234)

ci: unique remote github repo

---

.gitlab-ci.yml

Force the remote pr branch into the local one: Reset the existing local branch to the latest state of the pull request

ci: force the remote branch

---

mender/templates/api-gateway/deployment.yaml

You can choose to not to set either httpPort or httpsPort in the api_gateway, to prevent upload timeout with the Mender Cli, as reported by customers.
Ticket: MEN-7595

fix: traefik container ports optionals

---

.gitlab-ci.yml

The playground option is needed to run an EKS cluster to manually play with, and a Changelog job is useless here.

ci: not running changelog job during playground

---

.gitlab-ci.yml

Always get the full git history, to generate a full changelog without missing commits.
Ticket: None

ci: get full git history to generate changelog

---

release-please-config.json

Enable prerelease tags; this is the default for every master commit. If you want to create a stable release, you have to create a Release-As<colon> <your release version>
Ticket: QA-795

ci: prerelease support to release-please

---

.gitlab-ci.yml

At this stage the v4.0 tag has not yet been published. By using main, we should allow tests passing.
Please revert this commit after the new release is out
Ticket: None

ci: workaround missing v4.0 tag

---

tests/seaweedfs.yaml

For some reason, the data storage is not working with the default PVC and StorageClass. Falling back to emptyDir, is enough for the tests
Ticket: None

ci: fix seaweedfs filer data storage

---

.gitlab-ci.yml

The previous LTS tag was 3.6.5, not 3.6.6
Ticket: None

ci: using the right previous lts tag

---

.gitlab-ci.yml

The tests runs the useradm-enterprise command, which is not available in the new script. Since we don't need this test for now, let's temporary disable it.
Ticket: None

ci: temporary disable prev lts to curr lts test

---

mender/templates/api-gateway/deployment.yaml

In commit 9654235292dfeeeb0d1f9d203e5faffc5b9ed230 the https port was made optional, but the timeouts for https are still set regardless. This changes that.
This PR also adds timeouts for http, because those were missing and our artifact uploads going via nginx->api_gateway were failing after 60s.

Add http timeouts and only apply https timeouts when https is enabled

---

.gitlab-ci.yml

With these changes you can run release-please and git cliff on any protected (maintenance) branch. Moreover, switching to pre-baked release-please image

ci: run release-please on maintenance branches

---

.gitlab-ci.yml

To generate the changelog, include only the tags that belong to the current branch, useful for maintenance branches.
Ticket: None

ci: include only branch tags in the changelog

---

mender/values.yaml

The expression is using the former Traefik v2 regexp syntax.
Ticket: MEN-7741

fix: Invalid regexp in default value storage_proxy.customRule

---

README.md
mender/templates/deployments/_podtemplate.yaml
mender/values.yaml

With this override, you can choose a different secret for the deployments service, for example a secondary connection or a admin connection
Ticket: MEN-6493

feat: added mongodb secret override

---

mender/values-staging.yaml

These keys have been introduced by a faulty automation
Ticket: None

chore: cleanup wrong keys

---

mender/templates/deployments/_podtemplate.yaml
mender/values.yaml

Set storage.proxy_uri setting in deployments to the public URL {{.Values.global.url}}.
Ticket: MC-7739

fix: Use more sensible defaults when storage proxy is enabled

---

mender/values.yaml

Set default .Values.global.url to the sample public URL to avoid confusion.
Ticket: MC-7739
Follow up from: https://github.com/mendersoftware/mender-helm/pull/414/files

fix: Use sample global.url to avoid confusion

---

README.md
mender/templates/auditlogs/_podtemplate.yaml
mender/templates/deployments/_podtemplate.yaml
mender/templates/device-auth/_podtemplate.yaml
mender/templates/deviceconfig/_podtemplate.yaml
mender/templates/deviceconnect/_podtemplate.yaml
mender/templates/devicemonitor/_podtemplate.yaml
mender/templates/inventory/_podtemplate.yaml
mender/templates/iot-manager/_podtemplate.yaml
mender/templates/tenantadm/_podtemplate.yaml
mender/templates/useradm/_podtemplate.yaml
mender/templates/workflows/_podtemplate.yaml
mender/values.yaml

Extension of #417.
The internal addresses are uniquely determined from the name and port of
the respective service. They should not be configurable. The following
values have been removed and will be ineffectual:
- `device_auth.env.DEVICEAUTH_INVENTORY_ADDR`
- `device_auth.env.DEVICEAUTH_ORCHESTRATOR_ADDR`
- `device_auth.env.DEVICEAUTH_TENANTADM_ADDR`
- `useradm.env.USERADM_TENANTADM_ADDR`
- `devicemonitor.env.DEVICEMONITOR_USERADM_URL`
- `devicemonitor.env.DEVICEMONITOR_WORKFLOWS_URL`

Add missing internal addresses and replace values

---

mender/templates/api-gateway/configmap.yaml

Drops X-Forwarded-Host and X-Forwarded-Port when
`storage_proxy.enabled`.

chore: Workaround for SeaweedFS through storage proxy

---

release-please-config.json

The versioning key should be flipped to default, out of prerelease, to make actual stable releases every time, instead of prereleases.
Ticket: None

ci: switch to stable release for real

---

README.md
mender/templates/device-auth/cronjob_license_count.yaml
mender/templates/device-auth/cronjobs.yaml
mender/values.yaml

You can create custom cronjobs based on the deviceauth service. This feature is going to deprecate the device_license_count feature, that could be installed as a custom cronjob, with the provided example in the Values file.
The device_license_count key will be removed in the future.
Ticket: MC-7789

Optionals deviceauth cronjobs

---

.gitlab-ci.yml

Cloudflare R2 test is using protected variables; skipping this test when running non protected branches.
Ticket: QA-960

Don't run R2 tests with non protected branches

---

mender/templates/api-gateway/configmap.yaml
mender/templates/api-gateway/secret.yaml

We currently have nginx sitting in front of the api-gateway, doing SSL termination. It is also doing storage proxying, but we can move that to Traefik now with the latest release 😄 
We use cert-manager for our certificates, and currently we can't pass a secret cert-manager creates into the api-gateway, as it uses the wrong keys.
We prefer not to use k8's ingress, for a couple of reasons, so want to have Traefik serve the traffic directly

Switch api-gateway tls certificate to k8s tls type

---

README.md
mender/templates/api-gateway/configmap.yaml
mender/templates/api-gateway/secret.yaml
mender/values.yaml

Reintroducing the k8s TLS feature (commit 58687a0a22b809c8c6229f255a981165f8acb4bf) and  introducing the `featureGates.k8sTlsSecrets` option, to make that new feature as optional and avoiding breaking changes when using `api_gateway.certs.existingSecret`

Avoid breaking change with featureGates

---

mender/templates/deployments/cronjob.yaml

If mongodb secret is configured, cronjob will fail to start with error message `secret "mongodb-common" not found: CreateContainerConfigError`, since the hardcoded secret will be used instead of the configured one.
This should probably have been updated when this PR was submitted: https://github.com/mendersoftware/mender-helm/pull/392
Kubernetes deployment yaml looks like this, which is correct:
```yaml
...
envFrom:
- prefix: DEPLOYMENTS_
secretRef:
name: mender-mongodb-connection-url
...
```

fix(deployments): use mongodb secret variable if present

---

mender/templates/ingress.yaml

When templating the helm chart, the ingress doesn't came with a named namespace. This could be an issue when you apply the manifests generated from the helm template
Ticket: None

fix: set ingress namespace explicit

---

README.md
mender/templates/api-gateway/deployment.yaml
mender/templates/auditlogs/deployment.yaml
mender/templates/create-artifact-worker/deployment.yaml
mender/templates/deployments/deployment.yaml
mender/templates/device-auth/deployment.yaml
mender/templates/deviceconfig/deployment.yaml
mender/templates/deviceconnect/deployment.yaml
mender/templates/devicemonitor/deployment.yaml
mender/templates/generate-delta-worker/statefulset.yaml
mender/templates/gui/deployment.yaml
mender/templates/inventory/deployment.yaml
mender/templates/iot-manager/deployment.yaml
mender/templates/tenantadm/deployment.yaml
mender/templates/useradm/deployment.yaml
mender/templates/workflows/deployment-server.yaml
mender/templates/workflows/deployment-worker.yaml
mender/values.yaml

minReadySeconds could be useful when a new deployment came, and you have to coinsider the pod ready some time after the readinessProbe
Ticket: MC-7895

feat: add minReadySeconds

---

README.md
mender/templates/gui/deployment.yaml
mender/values.yaml

The gui container used to have a js minify build which has been refactored long ago and this waiting time is a leftover. Removing it.
Ticket: MC-8006

fix: avoid useless gui wait start

---

README.md
mender/templates/api-gateway/deployment.yaml
mender/values.yaml

We have a service that auto-reloads deployments when secrets/configmaps change (i.e cert-manager renews a certificate). See https://github.com/stakater/Reloader
We need to be able to set annotations on the api-gateway to support this, so I've added this into the template.
For completeness, if I add this to the api-gateway should I go through and add this option to all other k8s deployment templates?

api-gateway: add deployment annotations to template

---

mender/values.yaml

Don't specify both maxUnavailable and minAvailable which collide in a PodDisruptionBudget resource. By default only minAvailable: 1 is kept within the internal MongoDB.
Ticket: MC-8043

fix: mongodb poddistruptionbudget

---

mender/templates/api-gateway/configmap.yaml

This commit does not provide any visible change to the application, but allows routing to future experimental API endpoints.

fix(api-gateway): Relax routing version regex to allow experimental

---

mender/templates/api-gateway/configmap.yaml

To correctly expose the custom x-mender headers, we have to set them in the customResponseHeaders, instead of in the customRequestHeaders, which is for client to server communication only.
Ticket: MC-6867

fix: x-mender headers to customResponseHeaders

---

mender/templates/workflows/_podtemplate.yaml

**Description**
Set the `HAVE_DEVICEMONITOR` environment variable as required by https://github.com/mendersoftware/mender-server-enterprise/pull/642

MEN-5159: Set HAVE_DEVICEMONITOR env variable in workflows
